const AuthActionTypes = {
    SIGN_IN_SUCCESS: 'LOGIN_SUCCESS',
    SIGN_IN_FAILURE: 'LOGIN_ERROR',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_ERROR',
    SIGN_UP_SUCCESS: 'CREATE_USER_SUCCESS',
    SIGN_UP_FAILURE: 'CREATE_USER_ERROR'
  };
  
  export default AuthActionTypes;